<template>
  <div class="text-accent-content bg-accent-content/10 hidden">__</div>
  <div class="text-secondary-content bg-secondary-content/10 hidden">__</div>
  <div class="text-primary-content bg-primary-content/10 hidden">__</div>
  <div class="glass hidden">__</div>
  <div class="btn-accent hidden">__</div>
  <div class="text-info hidden">__</div>
  <div class="bg-info-focus hidden">__</div>
  <div class="bg-info hidden">__</div>
  <div class="bg-info/10 hidden">__</div>
  <div class="btn-info hidden">__</div>
  <div class="btn-secondary hidden">__</div>
  <div class="bg-primary/10 hidden">__</div>
  <div class="bg-primary-focus/10 hidden">__</div>
  <div class="btn-primary hidden">__</div>
  <div class="btn-info hidden">__</div>
  <div class="btn-error text-error bg-error hidden">__</div>
  <div class="btn-error text-error bg-error/10 hidden">__</div>
  <div class="btn-warning text-warning bg-warning hidden">__</div>
  <div class="btn-warning text-warning bg-warning/10 hidden">__</div>
  <div class="btn-success text-success bg-success hidden">__</div>
  <div class="btn-success text-success bg-success/10 hidden">__</div>
  <div class="text-secondary-content bg-secondary hidden">__</div>
  <div class="text-secondary-content bg-secondary/10 hidden">__</div>
  <div class="text-primary-focus bg-primary-focus hidden">__</div>
  <div class="text-primary-focus bg-primary-focus/10 hidden">__</div>
  <div class="text-accent bg-accent hidden">__</div>
  <div class="text-accent bg-accent/10 hidden">__</div>
  <div class="text-error bg-error-focus/10 hidden">__</div>
  <div class="text-info bg-info-focus/10 hidden">__</div>
  <div class="text-warning bg-warning-focus/10 hidden">__</div>
  <div class="text-warning bg-warning-focus/10 hidden">__</div>
  <div class="text-success bg-success-focus/10 hidden">__</div>
  <div class="text-secondary bg-secondary-focus/10 hidden">__</div>
  <div class="text-primary-content bg-accent-focus/10 hidden">__</div>

  <div class="hover:text-primary-focus hover:bg-primary hidden">__</div>
  <div class="hover:text-secondary-focus hover:bg-secondary hidden">__</div>
  <div class="hover:text-accent-focus hover:bg-accent hidden">__</div>
  <div class="hover:text-success-focus hover:bg-success hidden">__</div>
  <div class="hover:text-warning-focus hover:bg-warning hidden">__</div>
  <div class="hover:text-error-focus hover:bg-error hidden">__</div>
  <div class="hover:text-primary-focus hover:bg-primary/10 hidden">__</div>
  <div class="hover:text-secondary-focus hover:bg-secondary/10 hidden">__</div>
  <div class="hover:text-accent-focus hover:bg-accent/10 hidden">__</div>
  <div class="hover:text-success-focus hover:bg-success/10 hidden">__</div>
  <div class="hover:text-warning-focus hover:bg-warning/10 hidden">__</div>
  <div class="hover:text-error-focus hover:bg-error/10 hidden">__</div>
</template>
